const API_VERSION = '2026-09-10';
const THEMES = ['clarity','vita','medix','serenity','aurelia','tropica','urban','haven','noir','casa','savor','mesa'];
const CUSTOMER_HEADERS = ['id','name','business_name','category','email','whatsapp','city','address','tagline','description','logo_url','hero_image','gallery','services','instagram','facebook','website_id','status','created_at'];
const WEBSITE_HEADERS = ['website_id','customer_id','business_name','theme','repository','repository_url','website_url','status','created_at','updated_at'];

function doGet(){return json({success:true,data:{message:'Nakama CMS API is running',version:API_VERSION}});}
function doPost(e){try{const d=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}');switch(String(d.action||'').trim()){
case 'health':return json({success:true,data:{message:'API OK',version:API_VERSION}});
case 'init':return json({success:true,data:initSheets()});
case 'list_customers':return json({success:true,data:listCustomers()});
case 'create_customer':return json({success:true,data:createCustomer(d)});
case 'list_websites':return json({success:true,data:listWebsites()});
case 'generate_website':return json({success:true,data:generateWebsite(d)});
case 'deactivate_website':return json({success:true,data:deactivateWebsite(d)});
case 'activate_website':return json({success:true,data:activateWebsite(d)});
case 'delete_website':return json({success:true,data:deleteWebsite(d)});
default:return json({success:false,error:'Unknown action: '+d.action});}}catch(err){return json({success:false,error:err&&err.message?err.message:String(err)});}}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function config_(){const p=PropertiesService.getScriptProperties(),c={sheetId:String(p.getProperty('SHEET_ID')||'').trim(),githubToken:String(p.getProperty('GITHUB_TOKEN')||'').trim(),githubOwner:String(p.getProperty('GITHUB_OWNER')||'').trim(),sourceRepo:String(p.getProperty('GITHUB_SOURCE_REPO')||'').trim()};if(!c.sheetId)throw new Error('SHEET_ID belum diatur.');if(!c.githubToken)throw new Error('GITHUB_TOKEN belum diatur.');if(!c.githubOwner)throw new Error('GITHUB_OWNER belum diatur.');if(!c.sourceRepo)throw new Error('GITHUB_SOURCE_REPO belum diatur.');return c;}
function sheet_(name,headers){const sh=SpreadsheetApp.openById(config_().sheetId).getSheetByName(name)||SpreadsheetApp.openById(config_().sheetId).insertSheet(name);if(headers&&sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);return sh;}
function initSheets(){const ss=SpreadsheetApp.openById(config_().sheetId);let c=ss.getSheetByName('customers');if(!c){c=ss.insertSheet('customers');c.getRange(1,1,1,CUSTOMER_HEADERS.length).setValues([CUSTOMER_HEADERS]);}else migrateHeaders_(c,CUSTOMER_HEADERS);let w=ss.getSheetByName('websites');if(!w){w=ss.insertSheet('websites');w.getRange(1,1,1,WEBSITE_HEADERS.length).setValues([WEBSITE_HEADERS]);}else migrateHeaders_(w,WEBSITE_HEADERS);return{message:'Sheets initialized successfully',customer_fields:CUSTOMER_HEADERS,website_fields:WEBSITE_HEADERS};}
function migrateHeaders_(sh,headers){const current=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[];headers.forEach(function(h){if(current.indexOf(h)<0)sh.getRange(1,sh.getLastColumn()+1).setValue(h);});}
function objects_(name){const sh=sheet_(name);const v=sh.getDataRange().getValues();if(v.length<=1)return[];const h=v[0].map(String);return v.slice(1).map(function(r){const o={};h.forEach(function(k,i){o[k]=r[i];});return o;});}
function listCustomers(){initSheets();return objects_('customers');}
function listWebsites(){initSheets();return objects_('websites');}
function createCustomer(d){const sh=sheet_('customers',CUSTOMER_HEADERS);migrateHeaders_(sh,CUSTOMER_HEADERS);const id='CUST-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase();const name=s_(d.name),biz=s_(d.business_name);if(!name)throw new Error('Nama customer wajib diisi.');if(!biz)throw new Error('Nama bisnis wajib diisi.');const vals=[id,name,biz,s_(d.category),s_(d.email),s_(d.whatsapp),s_(d.city),s_(d.address),s_(d.tagline),s_(d.description),s_(d.logo_url),s_(d.hero_image),s_(d.gallery),s_(d.services),s_(d.instagram),s_(d.facebook),'','active',new Date().toISOString()];sh.appendRow(vals);return{id:id,name:name,business_name:biz,message:'Customer created successfully'};}
function generateWebsite(d){const cfg=config_(),cid=s_(d.customer_id),theme=s_(d.theme).toLowerCase();if(!cid)throw new Error('customer_id wajib diisi.');if(THEMES.indexOf(theme)<0)throw new Error('Theme tidak valid: '+theme);const customer=listCustomers().find(c=>s_(c.id)===cid);if(!customer)throw new Error('Customer tidak ditemukan: '+cid);const existing=listWebsites().find(w=>s_(w.customer_id)===cid&&s_(w.status)!=='deleted');if(existing&&existing.repository)throw new Error('Customer ini sudah memiliki website: '+existing.repository+'. Nonaktifkan/hapus website lama terlebih dahulu.');const repo=uniqueRepo_(customer.business_name);const repoUrl='https://github.com/'+cfg.githubOwner+'/'+repo;createRepository_(cfg,repo,customer.business_name);try{copyThemeToRepo_(cfg,theme,repo,customer);putConfigFile_(cfg,repo,customer);enablePages_(cfg,repo);}catch(e){throw new Error('Repository dibuat ('+repo+'), tetapi publish gagal: '+e.message);}const wid='WEB-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase(),url='https://'+cfg.githubOwner+'.github.io/'+repo+'/',now=new Date().toISOString();sheet_('websites',WEBSITE_HEADERS).appendRow([wid,cid,customer.business_name,theme,repo,repoUrl,url,'published',now,now]);updateCustomerWebsite_(cid,wid,'active');return{website_id:wid,customer_id:cid,repository:repo,repository_url:repoUrl,website_url:url,theme:theme,status:'published'};}
function deactivateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');if(s_(w.repository)){try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+s_(w.repository)+'/pages',null);}catch(e){if(!/404|not found/i.test(e.message))throw e;}}updateWebsiteStatus_(s_(w.website_id),'inactive');updateCustomerWebsite_(s_(w.customer_id),'','inactive');return{website_id:w.website_id,repository:w.repository,status:'inactive',message:'Website dinonaktifkan. Repository tetap aman dan dapat diaktifkan kembali.'};}
function activateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');if(!w.repository)throw new Error('Repository website tidak tersedia.');enablePages_(cfg,s_(w.repository));updateWebsiteStatus_(s_(w.website_id),'published');updateCustomerWebsite_(s_(w.customer_id),s_(w.website_id),'active');return{website_id:w.website_id,website_url:w.website_url,status:'published',message:'Website diaktifkan kembali.'};}
function deleteWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');const repo=s_(w.repository);if(repo){try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+repo,null);}catch(e){if(!/404|not found/i.test(e.message))throw e;}}updateWebsiteStatus_(s_(w.website_id),'deleted');updateCustomerWebsite_(s_(w.customer_id),'','active');return{website_id:w.website_id,repository:repo,status:'deleted',message:'Repository website dihapus dari GitHub dan record CMS ditandai deleted.'};}
function findWebsite_(d){const id=s_(d.website_id);const repo=s_(d.repository);return listWebsites().find(w=>(id&&s_(w.website_id)===id)||(repo&&s_(w.repository)===repo));}
function updateWebsiteStatus_(id,status){const sh=sheet_('websites',WEBSITE_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),ic=h.indexOf('website_id'),is=h.indexOf('status'),iu=h.indexOf('updated_at');for(let r=1;r<v.length;r++)if(s_(v[r][ic])===id){sh.getRange(r+1,is+1).setValue(status);if(iu>=0)sh.getRange(r+1,iu+1).setValue(new Date().toISOString());break;}}
function updateCustomerWebsite_(cid,wid,status){const sh=sheet_('customers',CUSTOMER_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),ic=h.indexOf('id'),iw=h.indexOf('website_id'),is=h.indexOf('status');for(let r=1;r<v.length;r++)if(s_(v[r][ic])===cid){if(iw>=0)sh.getRange(r+1,iw+1).setValue(wid);if(is>=0)sh.getRange(r+1,is+1).setValue(status);break;}}
function uniqueRepo_(name){let b=s_(name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'website';return'site-'+b+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toLowerCase();}
function github_(cfg,method,endpoint,payload){const o={method:method,muteHttpExceptions:true,headers:{Authorization:'Bearer '+cfg.githubToken,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}};if(payload!==undefined&&payload!==null){o.contentType='application/json';o.payload=JSON.stringify(payload);}const r=UrlFetchApp.fetch('https://api.github.com'+endpoint,o),st=r.getResponseCode(),t=r.getContentText();let b;try{b=JSON.parse(t);}catch(_){b={raw:t};}if(st<200||st>=300)throw new Error('GitHub API '+st+': '+(b.message||b.raw||t)+' ['+endpoint+']');return b;}
function getRef_(cfg,repo,ref){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/ref/'+encodeURIComponent(ref),null);}
function getCommit_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits/'+sha,null);}
function getTree_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees/'+sha+'?recursive=1',null);}
function getBlob_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs/'+sha,null);}
function sourceTree_(cfg,theme){const r=getRef_(cfg,cfg.sourceRepo,'heads/main'),c=getCommit_(cfg,cfg.sourceRepo,r.object.sha),t=getTree_(cfg,cfg.sourceRepo,c.tree.sha);return(t.tree||[]).filter(x=>x.type==='blob'&&x.path.indexOf('public/'+theme+'/')===0);}
function copyThemeToRepo_(cfg,theme,repo,customer){const src=sourceTree_(cfg,theme);if(!src.length)throw new Error('Theme public/'+theme+' tidak ditemukan.');const entries=src.map(function(item){const b=getBlob_(cfg,cfg.sourceRepo,item.sha);let enc=s_(b.content).replace(/\n/g,'');const rel=item.path.replace('public/'+theme+'/','');if(/\.html?$/i.test(rel)){let html=decode_(enc);html=buildCustomerHtml_(html,customer);enc=Utilities.base64Encode(Utilities.newBlob(html,'text/html').getBytes());}const nb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:enc,encoding:'base64'});return{path:rel,mode:'100644',type:'blob',sha:nb.sha};});const br=getRef_(cfg,repo,'heads/main'),bc=getCommit_(cfg,repo,br.object.sha),tr=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:bc.tree.sha,tree:entries}),cm=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Generate customer website from '+theme,tree:tr.sha,parents:[br.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:cm.sha,force:false});}
function buildCustomerHtml_(html,c){const business=escHtml_(s_(c.business_name)),desc=escHtml_(s_(c.description)||s_(c.tagline)||business+' — professional website'),city=escHtml_(s_(c.city)),addr=escHtml_(s_(c.address)),wa=normalizeWa_(s_(c.whatsapp)),inst=s_(c.instagram),fb=s_(c.facebook);html=html.replace(/<title>[^<]*<\/title>/i,'<title>'+business+(city?' | '+city:'')+'</title>');html=html.replace(/<meta\s+name=["']description["'][^>]*>/i,'<meta name="description" content="'+escAttr_(desc)+'">');html=html.replace(/<h1([^>]*)>[^<]*<\/h1>/i,'<h1$1 data-nakama="business-name">'+business+'</h1>');const cfg='<script src="js/nakama-site-config.js"></script><script src="js/nakama-site-runtime.js"></script>';html=html.replace(/<\/body>/i,cfg+'\n</body>');html=html.replace(/<body([^>]*)>/i,'<body$1 data-nakama-city="'+escAttr_(city)+'" data-nakama-address="'+escAttr_(addr)+'">');if(wa)html=html.replace(/href=["'](?:#|javascript:void\(0\)|tel:[^"']*)["']/gi,'href="https://wa.me/'+wa+'"');if(s_(c.hero_image))html=injectHero_(html,s_(c.hero_image));return html;}
function injectHero_(html,url){return html.replace(/(<img\b[^>]*)(src=["'])[^"']*(["'])/i,'$1$2'+escAttr_(url)+'$3');}
function putConfigFile_(cfg,repo,c){const data={businessName:s_(c.business_name),customerName:s_(c.name),category:s_(c.category),email:s_(c.email),whatsapp:s_(c.whatsapp),city:s_(c.city),address:s_(c.address),tagline:s_(c.tagline),description:s_(c.description),logoUrl:s_(c.logo_url),heroImage:s_(c.hero_image),gallery:s_(c.gallery),services:s_(c.services),instagram:s_(c.instagram),facebook:s_(c.facebook)};const runtime=`(function(){const d=${JSON.stringify(data)};window.NAKAMA_SITE=d;})();\n`;const configBlob=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob(runtime,'application/javascript').getBytes()),encoding:'base64'});const runtime=`${RUNTIME_JS}`;const rtBlob=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob(runtime,'application/javascript').getBytes()),encoding:'base64'});const ref=getRef_(cfg,repo,'heads/main'),commit=getCommit_(cfg,repo,ref.object.sha),tree=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:commit.tree.sha,tree:[{path:'js/nakama-site-config.js',mode:'100644',type:'blob',sha:configBlob.sha},{path:'js/nakama-site-runtime.js',mode:'100644',type:'blob',sha:rtBlob.sha}]});const nc=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Apply customer data and website runtime',tree:tree.sha,parents:[ref.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:nc.sha,force:false});}
function createRepository_(cfg,repo,biz){return github_(cfg,'post','/user/repos',{name:repo,description:'Website generated by Nakama Digital - '+s_(biz),private:false,has_issues:false,has_projects:false,has_wiki:false,auto_init:true});}
function enablePages_(cfg,repo){try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}});}catch(e){if(/already exists|already enabled|409/i.test(e.message))github_(cfg,'put','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}});else throw e;}try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages/builds',{});}catch(e){if(!/409|already|conflict/i.test(e.message))throw e;}Utilities.sleep(1200);}
function decode_(x){return Utilities.newBlob(Utilities.base64Decode(x)).getDataAsString('UTF-8');}
function s_(x){return String(x==null?'':x).trim();}
function escHtml_(x){return s_(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');}
function escAttr_(x){return escHtml_(x);}
function normalizeWa_(x){return s_(x).replace(/\D/g,'').replace(/^0/,'62');}

const RUNTIME_JS = `(function(){\nconst S=window.NAKAMA_SITE||{};\nconst q=(s)=>document.querySelector(s);\nconst all=(s)=>Array.prototype.slice.call(document.querySelectorAll(s));\nfunction setText(sel,val){if(!val)return;all(sel).forEach((e,i)=>{if(i<3)e.textContent=val;});}\nfunction wa(){let n=String(S.whatsapp||'').replace(/\\D/g,'').replace(/^0/,'62');return n?'https://wa.me/'+n:'';}\nfunction run(){document.title=S.businessName?(S.businessName+(S.city?' | '+S.city:'')):document.title;\nsetText('[data-nakama=business-name]',S.businessName);\nif(S.logoUrl)all('img').slice(0,1).forEach(i=>i.src=S.logoUrl);\nif(S.heroImage)all('img').slice(0,1).forEach(i=>i.src=S.heroImage);\nconst h=q('h1');if(h&&S.businessName)h.textContent=S.businessName;\nconst p=q('h1 + p');if(p&&(S.description||S.tagline))p.textContent=S.description||S.tagline;\nif(S.city)all('[class*=location],[class*=address]').forEach(e=>e.textContent=S.city+(S.address?', '+S.address:''));\nconst w=wa();if(w)all('a').forEach(a=>{const t=(a.textContent||'').toLowerCase();if(/book|reserve|contact|enquir|whatsapp|get started|make a reservation/.test(t))a.href=w;});\nif(S.email)all('a[href^=mailto:]').forEach(a=>a.href='mailto:'+S.email);\nif(S.instagram)all('a').forEach(a=>{if(/instagram/i.test(a.href||''))a.href=S.instagram;});\nif(S.facebook)all('a').forEach(a=>{if(/facebook/i.test(a.href||''))a.href=S.facebook;});\n}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();\n})();`;
