const API_VERSION='2026-09-10';
const THEMES=['clarity','vita','medix','serenity','aurelia','tropica','urban','haven','noir','casa','savor','mesa'];
const CUSTOMER_HEADERS=['id','name','business_name','category','email','whatsapp','city','address','tagline','description','logo_url','hero_image','gallery','services','instagram','facebook','website_id','status','created_at'];
const WEBSITE_HEADERS=['website_id','customer_id','business_name','theme','repository','repository_url','website_url','status','created_at','updated_at'];
function doGet(){return json({success:true,data:{message:'Nakama CMS API is running',version:API_VERSION}});}
function doPost(e){try{const d=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}');switch(String(d.action||'').trim()){case'health':return json({success:true,data:{message:'API OK',version:API_VERSION}});case'init':return json({success:true,data:initSheets()});case'list_customers':return json({success:true,data:listCustomers()});case'create_customer':return json({success:true,data:createCustomer(d)});case'list_websites':return json({success:true,data:listWebsites()});case'generate_website':return json({success:true,data:generateWebsite(d)});case'deactivate_website':return json({success:true,data:deactivateWebsite(d)});case'activate_website':return json({success:true,data:activateWebsite(d)});case'delete_website':return json({success:true,data:deleteWebsite(d)});default:return json({success:false,error:'Unknown action: '+d.action});}}catch(err){return json({success:false,error:err&&err.message?err.message:String(err)});}}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function config_(){const p=PropertiesService.getScriptProperties(),c={sheetId:String(p.getProperty('SHEET_ID')||'').trim(),githubToken:String(p.getProperty('GITHUB_TOKEN')||'').trim(),githubOwner:String(p.getProperty('GITHUB_OWNER')||'').trim(),sourceRepo:String(p.getProperty('GITHUB_SOURCE_REPO')||'').trim()};if(!c.sheetId)throw new Error('SHEET_ID belum diatur.');if(!c.githubToken)throw new Error('GITHUB_TOKEN belum diatur.');if(!c.githubOwner)throw new Error('GITHUB_OWNER belum diatur.');if(!c.sourceRepo)throw new Error('GITHUB_SOURCE_REPO belum diatur.');return c;}
function initSheets(){const ss=SpreadsheetApp.openById(config_().sheetId);let c=ss.getSheetByName('customers');if(!c){c=ss.insertSheet('customers');c.getRange(1,1,1,CUSTOMER_HEADERS.length).setValues([CUSTOMER_HEADERS]);}else migrateHeaders_(c,CUSTOMER_HEADERS);let w=ss.getSheetByName('websites');if(!w){w=ss.insertSheet('websites');w.getRange(1,1,1,WEBSITE_HEADERS.length).setValues([WEBSITE_HEADERS]);}else migrateHeaders_(w,WEBSITE_HEADERS);return{message:'Sheets initialized successfully'};}
function migrateHeaders_(sh,headers){const current=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[];headers.forEach(function(h){if(current.indexOf(h)<0)sh.getRange(1,sh.getLastColumn()+1).setValue(h);});}
function sheet_(name,headers){const ss=SpreadsheetApp.openById(config_().sheetId);let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(headers)migrateHeaders_(sh,headers);return sh;}
function objects_(name){const sh=sheet_(name);const v=sh.getDataRange().getValues();if(v.length<=1)return[];const h=v[0].map(String);return v.slice(1).map(function(r){const o={};h.forEach(function(k,i){o[k]=r[i];});return o;});}
function listCustomers(){initSheets();return objects_('customers');}
function listWebsites(){initSheets();return objects_('websites');}
function createCustomer(d){const sh=sheet_('customers',CUSTOMER_HEADERS),name=s_(d.name),biz=s_(d.business_name);if(!name)throw new Error('Nama customer wajib diisi.');if(!biz)throw new Error('Nama bisnis wajib diisi.');const id='CUST-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase();sh.appendRow([id,name,biz,s_(d.category),s_(d.email),s_(d.whatsapp),s_(d.city),s_(d.address),s_(d.tagline),s_(d.description),s_(d.logo_url),s_(d.hero_image),s_(d.gallery),s_(d.services),s_(d.instagram),s_(d.facebook),'','active',new Date().toISOString()]);return{id:id,name:name,business_name:biz,message:'Customer created successfully'};}
function generateWebsite(d){const cfg=config_(),cid=s_(d.customer_id),theme=s_(d.theme).toLowerCase();if(!cid)throw new Error('customer_id wajib diisi.');if(THEMES.indexOf(theme)<0)throw new Error('Theme tidak valid: '+theme);const customer=listCustomers().find(c=>s_(c.id)===cid);if(!customer)throw new Error('Customer tidak ditemukan: '+cid);const existing=listWebsites().find(w=>s_(w.customer_id)===cid&&s_(w.status)!=='deleted');if(existing&&existing.repository)throw new Error('Customer ini sudah memiliki website: '+existing.repository+'. Nonaktifkan atau hapus website lama terlebih dahulu.');const repo=uniqueRepo_(customer.business_name),repoUrl='https://github.com/'+cfg.githubOwner+'/'+repo;createRepository_(cfg,repo,customer.business_name);try{copyThemeToRepo_(cfg,theme,repo,customer);putConfigFile_(cfg,repo,customer,theme);enablePages_(cfg,repo);}catch(e){throw new Error('Repository dibuat ('+repo+'), tetapi publish gagal: '+e.message);}const wid='WEB-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase(),url='https://'+cfg.githubOwner+'.github.io/'+repo+'/',now=new Date().toISOString();sheet_('websites',WEBSITE_HEADERS).appendRow([wid,cid,customer.business_name,theme,repo,repoUrl,url,'published',now,now]);updateCustomerWebsite_(cid,wid);return{website_id:wid,customer_id:cid,repository:repo,repository_url:repoUrl,website_url:url,theme:theme,status:'published'};}
function deactivateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+s_(w.repository)+'/pages',null);}catch(e){if(!/404|not found/i.test(e.message))throw e;}updateWebsiteStatus_(s_(w.website_id),'inactive');return{website_id:w.website_id,repository:w.repository,status:'inactive',message:'Website dinonaktifkan. Repository tetap ada.'};}
function activateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');enablePages_(cfg,s_(w.repository));updateWebsiteStatus_(s_(w.website_id),'published');return{website_id:w.website_id,website_url:w.website_url,status:'published',message:'Website diaktifkan kembali.'};}
function deleteWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');const repo=s_(w.repository);if(repo){try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+repo,null);}catch(e){if(!/404|not found/i.test(e.message))throw e;}}updateWebsiteStatus_(s_(w.website_id),'deleted');updateCustomerWebsite_(s_(w.customer_id),'');return{website_id:w.website_id,repository:repo,status:'deleted',message:'Repository GitHub dihapus dan record CMS ditandai deleted.'};}
function findWebsite_(d){const id=s_(d.website_id),repo=s_(d.repository);return listWebsites().find(w=>(id&&s_(w.website_id)===id)||(repo&&s_(w.repository)===repo));}
function updateWebsiteStatus_(id,status){const sh=sheet_('websites',WEBSITE_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),ic=h.indexOf('website_id'),is=h.indexOf('status'),iu=h.indexOf('updated_at');for(let r=1;r<v.length;r++)if(s_(v[r][ic])===id){sh.getRange(r+1,is+1).setValue(status);if(iu>=0)sh.getRange(r+1,iu+1).setValue(new Date().toISOString());break;}}
function updateCustomerWebsite_(cid,wid){const sh=sheet_('customers',CUSTOMER_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),ic=h.indexOf('id'),iw=h.indexOf('website_id');for(let r=1;r<v.length;r++)if(s_(v[r][ic])===cid){if(iw>=0)sh.getRange(r+1,iw+1).setValue(wid||'');break;}}
function uniqueRepo_(name){const b=s_(name).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'website';return'site-'+b+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toLowerCase();}
function github_(cfg,method,endpoint,payload){const o={method:method,muteHttpExceptions:true,headers:{Authorization:'Bearer '+cfg.githubToken,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}};if(payload!==undefined&&payload!==null){o.contentType='application/json';o.payload=JSON.stringify(payload);}const r=UrlFetchApp.fetch('https://api.github.com'+endpoint,o),st=r.getResponseCode(),t=r.getContentText();let b;try{b=JSON.parse(t);}catch(_){b={raw:t};}if(st<200||st>=300)throw new Error('GitHub API '+st+': '+(b.message||b.raw||t)+' ['+endpoint+']');return b;}
function getRef_(cfg,repo,ref){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/ref/'+encodeURIComponent(ref),null);}
function getCommit_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits/'+sha,null);}
function getTree_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees/'+sha+'?recursive=1',null);}
function getBlob_(cfg,repo,sha){return github_(cfg,'get','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs/'+sha,null);}
function sourceTree_(cfg,theme){const r=getRef_(cfg,cfg.sourceRepo,'heads/main'),c=getCommit_(cfg,cfg.sourceRepo,r.object.sha),t=getTree_(cfg,cfg.sourceRepo,c.tree.sha);return(t.tree||[]).filter(x=>x.type==='blob'&&x.path.indexOf('public/'+theme+'/')===0);}
function copyThemeToRepo_(cfg,theme,repo,customer){const src=sourceTree_(cfg,theme);if(!src.length)throw new Error('Theme public/'+theme+' tidak ditemukan.');const entries=src.map(function(item){const b=getBlob_(cfg,cfg.sourceRepo,item.sha);let enc=s_(b.content).replace(/\n/g,'');const rel=item.path.replace('public/'+theme+'/','');if(/\.html?$/i.test(rel)){let html=decode_(enc);html=buildCustomerHtml_(html,customer,theme);enc=Utilities.base64Encode(Utilities.newBlob(html,'text/html').getBytes());}const nb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:enc,encoding:'base64'});return{path:rel,mode:'100644',type:'blob',sha:nb.sha};});const br=getRef_(cfg,repo,'heads/main'),bc=getCommit_(cfg,repo,br.object.sha),tr=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:bc.tree.sha,tree:entries}),cm=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Generate customer website from '+theme,tree:tr.sha,parents:[br.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:cm.sha,force:false});}
function buildCustomerHtml_(html,c,theme){const business=escHtml_(s_(c.business_name)),desc=escHtml_(s_(c.description)||s_(c.tagline)||business+' — professional website'),city=escHtml_(s_(c.city)),addr=escHtml_(s_(c.address)),wa=normalizeWa_(s_(c.whatsapp));html=html.replace(/<title>[^<]*<\/title>/i,'<title>'+business+(city?' | '+city:'')+'</title>');html=html.replace(/<meta\s+name=["']description["'][^>]*>/i,'<meta name="description" content="'+escAttr_(desc)+'">');html=html.replace(/<body([^>]*)>/i,'<body$1 data-nakama-city="'+escAttr_(city)+'" data-nakama-address="'+escAttr_(addr)+'">');if(wa)html=html.replace(/href=["'](?:#|javascript:void\(0\)|tel:[^"']*)["']/gi,'href="https://wa.me/'+wa+'"');if(s_(c.hero_image))html=injectHero_(html,s_(c.hero_image));const scripts='<script src="js/nakama-site-config.js"></script><script src="js/nakama-site-runtime.js"></script>';html=html.replace(/<\/body>/i,scripts+'\n</body>');return html;}
function injectHero_(html,url){return html.replace(/(<img\b[^>]*)(src=["'])[^"']*(["'])/i,'$1$2'+escAttr_(url)+'$3');}
function putConfigFile_(cfg,repo,c,theme){const data={businessName:s_(c.business_name),customerName:s_(c.name),category:s_(c.category),email:s_(c.email),whatsapp:s_(c.whatsapp),city:s_(c.city),address:s_(c.address),tagline:s_(c.tagline),description:s_(c.description),logoUrl:s_(c.logo_url),heroImage:s_(c.hero_image),gallery:s_(c.gallery),services:s_(c.services),instagram:s_(c.instagram),facebook:s_(c.facebook),theme:theme};const configText='window.NAKAMA_SITE='+JSON.stringify(data)+';';const configBlob=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob(configText,'application/javascript').getBytes()),encoding:'base64'});const runtimeBlob=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob(RUNTIME_JS,'application/javascript').getBytes()),encoding:'base64'});const ref=getRef_(cfg,repo,'heads/main'),commit=getCommit_(cfg,repo,ref.object.sha),tree=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:commit.tree.sha,tree:[{path:'js/nakama-site-config.js',mode:'100644',type:'blob',sha:configBlob.sha},{path:'js/nakama-site-runtime.js',mode:'100644',type:'blob',sha:runtimeBlob.sha}]}),nc=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Apply customer content runtime',tree:tree.sha,parents:[ref.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:nc.sha,force:false});}
function createRepository_(cfg,repo,biz){return github_(cfg,'post','/user/repos',{name:repo,description:'Website generated by Nakama Digital - '+s_(biz),private:false,has_issues:false,has_projects:false,has_wiki:false,auto_init:true});}
function enablePages_(cfg,repo){try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}});}catch(e){if(/already exists|already enabled|409/i.test(e.message))github_(cfg,'put','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}});else throw e;}try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages/builds',{});}catch(e){if(!/409|already|conflict/i.test(e.message))throw e;}Utilities.sleep(1200);}
function decode_(x){return Utilities.newBlob(Utilities.base64Decode(x)).getDataAsString('UTF-8');}
function s_(x){return String(x==null?'':x).trim();}
function escHtml_(x){return s_(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');}
function escAttr_(x){return escHtml_(x);}
function normalizeWa_(x){return s_(x).replace(/\D/g,'').replace(/^0/,'62');}
const RUNTIME_JS=`(function(){const S=window.NAKAMA_SITE||{};const A=s=>Array.prototype.slice.call(document.querySelectorAll(s));const txt=(s,v)=>{if(v)A(s).forEach(e=>e.textContent=v)};function wa(){let n=String(S.whatsapp||'').replace(/\\D/g,'').replace(/^0/,'62');return n?'https://wa.me/'+n:''}function replaceThemeName(){if(!S.theme||!S.businessName)return;const names={clarity:['Clarity'],vita:['Vita'],medix:['Medix'],serenity:['Serenity'],aurelia:['Aurelia'],tropica:['Tropica'],urban:['Urban'],haven:['Haven'],noir:['Noir'],casa:['Casa'],savor:['Savor'],mesa:['Mesa']}[S.theme]||[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{let v=n.nodeValue;names.forEach(x=>{v=v.replace(new RegExp(x,'gi'),S.businessName)});n.nodeValue=v})}function run(){if(S.businessName)document.title=S.businessName+(S.city?' | '+S.city:'');txt('.brand',S.businessName);const h=document.querySelector('h1');if(h&&S.businessName)h.textContent=S.tagline||S.businessName;txt('.hero-title',S.tagline||S.businessName);txt('.intro .section-subtitle','Welcome to '+S.businessName);txt('.intro .section-desc,.about .section-desc',S.description||S.tagline);txt('.overlay-info p:nth-child(1)',S.address||S.city);txt('.overlay-info p:nth-child(2)',S.email);txt('.overlay-info p:nth-child(3)',S.whatsapp);txt('.footer-brand .brand',S.businessName);if(S.logoUrl)A('img').slice(0,1).forEach(i=>{i.src=S.logoUrl;i.alt=S.businessName});if(S.heroImage)A('.hero img').slice(0,1).forEach(i=>{i.src=S.heroImage;i.alt=S.businessName});if(S.city)A('[class*=location],[class*=address]').forEach(e=>e.textContent=S.city+(S.address?', '+S.address:''));const w=wa();if(w)A('a').forEach(a=>{const t=(a.textContent||'').toLowerCase();if(/book|reserve|contact|enquir|whatsapp|get started|make a reservation|discover more|explore/.test(t))a.href=w});if(S.email)A('a[href^=mailto:]').forEach(a=>a.href='mailto:'+S.email);if(S.instagram)A('a').forEach(a=>{if(/instagram/i.test(a.textContent||'')||/instagram/i.test(a.href||''))a.href=S.instagram});if(S.facebook)A('a').forEach(a=>{if(/facebook/i.test(a.textContent||'')||/facebook/i.test(a.href||''))a.href=S.facebook});const services=String(S.services||'').split(/[,\\n]+/).map(x=>x.trim()).filter(Boolean);if(services.length){A('.facility-item h4,.room-info h3,.dining-list h4').forEach((e,i)=>{if(services[i])e.textContent=services[i]});}if(S.description){A('.room-desc,.dining-content .section-desc').forEach(e=>e.textContent=S.description);}replaceThemeName()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();})();`;
