const API_VERSION='2026-09-10-v2';
const THEMES=['clarity','vita','medix','serenity','aurelia','tropica','urban','haven','noir','casa','savor','mesa'];
const THEME_CATEGORY={clarity:'Clinic',vita:'Clinic',medix:'Clinic',serenity:'Clinic',aurelia:'Hotel',tropica:'Hotel',urban:'Hotel',haven:'Hotel',noir:'Restaurant',casa:'Restaurant',savor:'Restaurant',mesa:'Restaurant'};
const CUSTOMER_HEADERS=['id','name','business_name','category','email','whatsapp','city','address','tagline','description','category_data','assets','instagram','facebook','website_id','status','created_at'];
const WEBSITE_HEADERS=['website_id','customer_id','business_name','theme','repository','repository_url','website_url','status','created_at','updated_at'];
function doGet(){return json({success:true,data:{message:'Nakama CMS API is running',version:API_VERSION}})}
function doPost(e){try{const d=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}');switch(String(d.action||'').trim()){case'health':return json({success:true,data:{message:'API OK',version:API_VERSION}});case'init':return json({success:true,data:initSheets()});case'list_customers':return json({success:true,data:listCustomers()});case'create_customer':return json({success:true,data:createCustomer(d)});case'upload_asset':return json({success:true,data:uploadAsset(d)});case'list_websites':return json({success:true,data:listWebsites()});case'generate_website':return json({success:true,data:generateWebsite(d)});case'deactivate_website':return json({success:true,data:deactivateWebsite(d)});case'activate_website':return json({success:true,data:activateWebsite(d)});case'delete_website':return json({success:true,data:deleteWebsite(d)});default:return json({success:false,error:'Unknown action: '+d.action})}}catch(err){return json({success:false,error:err&&err.message?err.message:String(err)})}}
function json(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function config_(){const p=PropertiesService.getScriptProperties(),c={sheetId:s_(p.getProperty('SHEET_ID')),githubToken:s_(p.getProperty('GITHUB_TOKEN')),githubOwner:s_(p.getProperty('GITHUB_OWNER')),sourceRepo:s_(p.getProperty('GITHUB_SOURCE_REPO'))};if(!c.sheetId||!c.githubToken||!c.githubOwner||!c.sourceRepo)throw new Error('SHEET_ID, GITHUB_TOKEN, GITHUB_OWNER, dan GITHUB_SOURCE_REPO wajib diatur.');return c}
function initSheets(){const ss=SpreadsheetApp.openById(config_().sheetId);let c=ss.getSheetByName('customers');if(!c){c=ss.insertSheet('customers');c.getRange(1,1,1,CUSTOMER_HEADERS.length).setValues([CUSTOMER_HEADERS])}else migrate_(c,CUSTOMER_HEADERS);let w=ss.getSheetByName('websites');if(!w){w=ss.insertSheet('websites');w.getRange(1,1,1,WEBSITE_HEADERS.length).setValues([WEBSITE_HEADERS])}else migrate_(w,WEBSITE_HEADERS);return{message:'Sheets initialized successfully'}}
function migrate_(sh,h){const cur=sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String):[];h.forEach(x=>{if(cur.indexOf(x)<0)sh.getRange(1,sh.getLastColumn()+1).setValue(x)})}
function sheet_(n,h){const ss=SpreadsheetApp.openById(config_().sheetId);let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(h)migrate_(sh,h);return sh}
function objects_(n){const sh=sheet_(n),v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(String);return v.slice(1).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o})}
function listCustomers(){initSheets();return objects_('customers')}
function listWebsites(){initSheets();return objects_('websites')}
function createCustomer(d){const sh=sheet_('customers',CUSTOMER_HEADERS),id='CUST-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase(),name=s_(d.name),biz=s_(d.business_name),cat=s_(d.category);if(!name||!biz||!cat)throw new Error('Nama pemilik, nama bisnis, dan kategori wajib diisi.');const row=sh.getLastRow()+1,h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),o={id,name,business_name:biz,category:cat,email:s_(d.email),whatsapp:s_(d.whatsapp),city:s_(d.city),address:s_(d.address),tagline:s_(d.tagline),description:s_(d.description),category_data:JSON.stringify(d.category_data||{}),assets:'{}',instagram:s_(d.instagram),facebook:s_(d.facebook),website_id:'',status:'active',created_at:new Date().toISOString()};sh.getRange(row,1,1,h.length).setValues([h.map(k=>o[k]!==undefined?o[k]:'')]);return{id,name,business_name:biz,category:cat,message:'Customer created successfully'}}
function uploadAsset(d){const cid=s_(d.customer_id),kind=s_(d.kind),name=s_(d.filename).replace(/[^a-zA-Z0-9._-]/g,'-'),mime=s_(d.mime)||'application/octet-stream',b64=s_(d.base64);if(!cid||!kind||!name||!b64)throw new Error('Data upload tidak lengkap.');if(b64.length>8*1024*1024)throw new Error('File terlalu besar. Maksimum 5 MB per file.');const customer=listCustomers().find(x=>s_(x.id)===cid);if(!customer)throw new Error('Customer tidak ditemukan.');const root=getOrCreateAssetFolder_(cid,customer.business_name),folder=getOrCreateFolder_(root,kind),file=folder.createFile(Utilities.newBlob(Utilities.base64Decode(b64),mime,name)),row=findCustomerRow_(cid),assets=parseJson_(row.assets,{});if(!assets[kind])assets[kind]=[];assets[kind].push({id:file.getId(),name:file.getName(),mime:file.getMimeType(),size:file.getSize()});setCustomerCell_(cid,'assets',JSON.stringify(assets));return{id:file.getId(),name:file.getName(),kind,message:'Upload berhasil'}}
function getOrCreateAssetFolder_(cid,biz){const p=PropertiesService.getScriptProperties(),key='NAKAMA_ASSET_FOLDER_'+cid;let f=null,id=p.getProperty(key);if(id)try{f=DriveApp.getFolderById(id)}catch(_){}if(!f){const roots=DriveApp.getFoldersByName('Nakama CMS Assets'),root=roots.hasNext()?roots.next():DriveApp.createFolder('Nakama CMS Assets');f=root.createFolder(safeName_(biz)+'-'+cid);p.setProperty(key,f.getId())}return f}
function getOrCreateFolder_(p,n){const i=p.getFoldersByName(n);return i.hasNext()?i.next():p.createFolder(n)}
function generateWebsite(d){const cfg=config_(),cid=s_(d.customer_id),theme=s_(d.theme).toLowerCase(),customer=listCustomers().find(x=>s_(x.id)===cid);if(THEMES.indexOf(theme)<0)throw new Error('Theme tidak valid: '+theme);if(!customer)throw new Error('Customer tidak ditemukan.');if(s_(customer.category).toLowerCase()!==s_(THEME_CATEGORY[theme]).toLowerCase())throw new Error('Theme '+theme+' tidak sesuai kategori customer '+customer.category+'.');if(listWebsites().some(w=>s_(w.customer_id)===cid&&s_(w.status)!=='deleted'))throw new Error('Customer ini sudah memiliki website. Nonaktifkan atau hapus website lama terlebih dahulu.');const repo=uniqueRepo_(customer.business_name),repoUrl='https://github.com/'+cfg.githubOwner+'/'+repo;createRepository_(cfg,repo,customer.business_name);try{copyTheme_(cfg,theme,repo,customer);putConfig_(cfg,repo,customer,theme);enablePages_(cfg,repo)}catch(e){throw new Error('Repository dibuat ('+repo+'), tetapi publish gagal: '+e.message)}const wid='WEB-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase(),url='https://'+cfg.githubOwner+'.github.io/'+repo+'/',now=new Date().toISOString();sheet_('websites',WEBSITE_HEADERS).appendRow([wid,cid,customer.business_name,theme,repo,repoUrl,url,'published',now,now]);updateCustomerWebsite_(cid,wid);return{website_id:wid,customer_id:cid,repository:repo,repository_url:repoUrl,website_url:url,theme,status:'published'}}
function copyTheme_(cfg,theme,repo,c){const src=sourceTree_(cfg,theme);if(!src.length)throw new Error('Theme tidak ditemukan.');const entries=src.map(item=>{const b=getBlob_(cfg,cfg.sourceRepo,item.sha),rel=item.path.replace('public/'+theme+'/','');let enc=s_(b.content).replace(/\n/g,'');if(/\.html?$/i.test(rel)){let html=decode_(enc);html=prepareHtml_(html,c);enc=Utilities.base64Encode(Utilities.newBlob(html,'text/html').getBytes())}const nb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:enc,encoding:'base64'});return{path:rel,mode:'100644',type:'blob',sha:nb.sha}});const br=getRef_(cfg,repo,'heads/main'),bc=getCommit_(cfg,repo,br.object.sha),tr=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:bc.tree.sha,tree:entries}),cm=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Generate customer website from '+theme,tree:tr.sha,parents:[br.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:cm.sha,force:false})}
function prepareHtml_(html,c){const title=escHtml_(s_(c.business_name)),desc=escAttr_(s_(c.description)||s_(c.tagline)||c.business_name);html=html.replace(/<title>[^<]*<\/title>/i,'<title>'+title+(c.city?' | '+escHtml_(c.city):'')+'</title>').replace(/<meta\s+name=["']description["'][^>]*>/i,'<meta name="description" content="'+desc+'">');html=html.replace(/<body([^>]*)>/i,'<body$1 data-nakama-business="'+escAttr_(c.business_name)+'">');html=html.replace(/<\/body>/i,'<script src="js/nakama-site-config.js"></script><script src="js/nakama-site-runtime.js"></script>\n</body>');return html}
function putConfig_(cfg,repo,c,theme){const data={businessName:s_(c.business_name),customerName:s_(c.name),category:s_(c.category),email:s_(c.email),whatsapp:normalizeWa_(c.whatsapp),city:s_(c.city),address:s_(c.address),tagline:s_(c.tagline),description:s_(c.description),categoryData:parseJson_(c.category_data,{}),assets:parseJson_(c.assets,{}),instagram:s_(c.instagram),facebook:s_(c.facebook),theme};const cb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob('window.NAKAMA_SITE='+JSON.stringify(data)+';','application/javascript').getBytes()),encoding:'base64'}),rb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:Utilities.base64Encode(Utilities.newBlob(RUNTIME_JS,'application/javascript').getBytes()),encoding:'base64'}),ref=getRef_(cfg,repo,'heads/main'),co=getCommit_(cfg,repo,ref.object.sha),tr=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:co.tree.sha,tree:[{path:'js/nakama-site-config.js',mode:'100644',type:'blob',sha:cb.sha},{path:'js/nakama-site-runtime.js',mode:'100644',type:'blob',sha:rb.sha}]}),cm=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Apply customer data runtime',tree:tr.sha,parents:[ref.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:cm.sha,force:false});uploadAssetsToRepo_(cfg,repo,data.assets)}
function uploadAssetsToRepo_(cfg,repo,assets){const all=[];Object.keys(assets||{}).forEach(k=>(assets[k]||[]).forEach(x=>all.push({kind:k,id:x.id,name:x.name,mime:x.mime})));if(!all.length)return;const entries=all.map(x=>{const f=DriveApp.getFileById(x.id),b64=Utilities.base64Encode(f.getBlob().getBytes()),nb=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/blobs',{content:b64,encoding:'base64'});return{path:'assets/'+x.kind+'/'+safeName_(x.name),mode:'100644',type:'blob',sha:nb.sha}});const ref=getRef_(cfg,repo,'heads/main'),co=getCommit_(cfg,repo,ref.object.sha),tr=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/trees',{base_tree:co.tree.sha,tree:entries}),cm=github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/git/commits',{message:'Add customer media assets',tree:tr.sha,parents:[ref.object.sha]});github_(cfg,'patch','/repos/'+cfg.githubOwner+'/'+repo+'/git/refs/heads/main',{sha:cm.sha,force:false})}
function deactivateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+w.repository+'/pages',null)}catch(e){if(!/404|not found/i.test(e.message))throw e}updateWebsiteStatus_(w.website_id,'inactive');return{website_id:w.website_id,status:'inactive',message:'Website dinonaktifkan. Repository tetap ada.'}}
function activateWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');enablePages_(cfg,w.repository);updateWebsiteStatus_(w.website_id,'published');return{website_id:w.website_id,website_url:w.website_url,status:'published',message:'Website diaktifkan kembali.'}}
function deleteWebsite(d){const cfg=config_(),w=findWebsite_(d);if(!w)throw new Error('Website tidak ditemukan.');try{github_(cfg,'delete','/repos/'+cfg.githubOwner+'/'+w.repository,null)}catch(e){if(!/404|not found/i.test(e.message))throw e}updateWebsiteStatus_(w.website_id,'deleted');updateCustomerWebsite_(w.customer_id,'');return{website_id:w.website_id,status:'deleted',message:'Repository GitHub dihapus dan record ditandai deleted.'}}
function findWebsite_(d){return listWebsites().find(w=>(d.website_id&&s_(w.website_id)===s_(d.website_id))||(d.repository&&s_(w.repository)===s_(d.repository)))}
function updateWebsiteStatus_(id,st){const sh=sheet_('websites',WEBSITE_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),i=h.indexOf('website_id'),s=h.indexOf('status'),u=h.indexOf('updated_at');for(let r=1;r<v.length;r++)if(s_(v[r][i])===s_(id)){sh.getRange(r+1,s+1).setValue(st);if(u>=0)sh.getRange(r+1,u+1).setValue(new Date().toISOString());break}}
function updateCustomerWebsite_(cid,wid){setCustomerCell_(cid,'website_id',wid||'')}
function setCustomerCell_(cid,col,val){const sh=sheet_('customers',CUSTOMER_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),i=h.indexOf('id'),j=h.indexOf(col);for(let r=1;r<v.length;r++)if(s_(v[r][i])===s_(cid)){sh.getRange(r+1,j+1).setValue(val);break}}
function findCustomerRow_(cid){const sh=sheet_('customers',CUSTOMER_HEADERS),v=sh.getDataRange().getValues(),h=v[0].map(String),i=h.indexOf('id'),a=h.indexOf('assets');for(let r=1;r<v.length;r++)if(s_(v[r][i])===s_(cid))return{row:r+1,assets:v[r][a]};throw new Error('Customer tidak ditemukan.')}
function createRepository_(cfg,repo,biz){return github_(cfg,'post','/user/repos',{name:repo,description:'Website generated by Nakama Digital - '+s_(biz),private:false,has_issues:false,has_projects:false,has_wiki:false,auto_init:true})}
function enablePages_(cfg,repo){try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}})}catch(e){if(/already exists|already enabled|409/i.test(e.message))github_(cfg,'put','/repos/'+cfg.githubOwner+'/'+repo+'/pages',{source:{branch:'main',path:'/'}});else throw e}try{github_(cfg,'post','/repos/'+cfg.githubOwner+'/'+repo+'/pages/builds',{})}catch(e){if(!/409|already|conflict/i.test(e.message))throw e}Utilities.sleep(1000)}
function sourceTree_(cfg,theme){const r=getRef_(cfg,cfg.sourceRepo,'heads/main'),c=getCommit_(cfg,cfg.sourceRepo,r.object.sha),t=getTree_(cfg,cfg.sourceRepo,c.tree.sha);return(t.tree||[]).filter(x=>x.type==='blob'&&x.path.indexOf('public/'+theme+'/')===0)}
function getRef_(c,r,f){return github_(c,'get','/repos/'+c.githubOwner+'/'+r+'/git/ref/'+encodeURIComponent(f),null)}function getCommit_(c,r,s){return github_(c,'get','/repos/'+c.githubOwner+'/'+r+'/git/commits/'+s,null)}function getTree_(c,r,s){return github_(c,'get','/repos/'+c.githubOwner+'/'+r+'/git/trees/'+s+'?recursive=1',null)}function getBlob_(c,r,s){return github_(c,'get','/repos/'+c.githubOwner+'/'+r+'/git/blobs/'+s,null)}
function github_(cfg,m,e,p){const o={method:m,muteHttpExceptions:true,headers:{Authorization:'Bearer '+cfg.githubToken,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}};if(p!==undefined&&p!==null){o.contentType='application/json';o.payload=JSON.stringify(p)}const r=UrlFetchApp.fetch('https://api.github.com'+e,o),st=r.getResponseCode(),t=r.getContentText();let b;try{b=JSON.parse(t)}catch(_){b={raw:t}}if(st<200||st>=300)throw new Error('GitHub API '+st+': '+(b.message||b.raw||t)+' ['+e+']');return b}
function uniqueRepo_(n){const b=s_(n).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'website';return'site-'+b+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toLowerCase()}
function safeName_(n){return s_(n).replace(/[^a-zA-Z0-9._-]/g,'-')}function parseJson_(x,d){try{return JSON.parse(s_(x)||'null')||d}catch(_){return d}}function s_(x){return String(x==null?'':x).trim()}function escHtml_(x){return s_(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}function escAttr_(x){return escHtml_(x)}function normalizeWa_(x){let n=s_(x).replace(/\D/g,'');if(n.startsWith('0'))n='62'+n.slice(1);return n}
const RUNTIME_JS=String.raw`(function(){const d=window.NAKAMA_SITE||{},c=d.categoryData||{},A=d.assets||{};const q=s=>document.querySelector(s),qa=s=>Array.from(document.querySelectorAll(s));function txt(e,v){if(e&&v!==undefined&&v!==null)e.textContent=v}function img(s,u){const e=q(s);if(e&&u)e.src=u}const brand=d.businessName||'Business';qa('.brand').forEach(e=>txt(e,brand));if(d.tagline)txt(q('.hero-title'),d.tagline);else txt(q('.hero-title'),brand);if(d.description)txt(q('.intro .section-desc')||q('.intro p'),d.description);if(A.logo&&A.logo[0])qa('img').filter(e=>/logo|brand/i.test((e.alt||'')+' '+(e.className||''))).forEach(e=>e.src='assets/logo/'+A.logo[0].name);if(A.hero&&A.hero[0])img('.hero img','assets/hero/'+A.hero[0].name);if(A.gallery&&A.gallery.length)qa('.gallery img').forEach((e,i)=>{if(A.gallery[i])e.src='assets/gallery/'+A.gallery[i].name});qa('a[href="#"]').forEach(a=>{const t=(a.textContent||'').toLowerCase();if(d.whatsapp&&(t.includes('book')||t.includes('reserve')||t.includes('contact')||t.includes('order')||t.includes('availability')))a.href='https://wa.me/'+d.whatsapp});qa('body *').forEach(e=>{if(e.children.length===0&&e.textContent){let x=e.textContent;x=x.replace(/Aurelia/g,d.businessName||'').replace(/Paris, France/g,d.city||'').replace(/123 Luxury Avenue/g,d.address||'').replace(/contact@aureliahotel\.com/ig,d.email||'');if(x!==e.textContent)e.textContent=x}});})();`;
